version: "3.7"

services:
  mongodb:
    image: "bitnami/mongodb:latest"
    volumes:
      - "./mongodb_data:/bitnami"

  countly-api:
    user: 0:0
    restart: always
    image: "countly/api:${SOFTWARE_VERSION_TAG}"
    environment:
      - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager
      - COUNTLY_CONFIG__MONGODB_HOST=mongodb
      - COUNTLY_CONFIG_API_API_WORKERS=4 # CPU core count
      - COUNTLY_CONFIG__FILESTORAGE="gridfs"
      - NODE_OPTIONS="--max-old-space-size=2048"
    depends_on:
      - mongodb
    volumes:
      - ./mail.js:/opt/countly/extend/mail.js

  countly-frontend:
    user: 0:0
    restart: always
    image: "countly/frontend:${SOFTWARE_VERSION_TAG}"
    environment:
      - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager
      - COUNTLY_CONFIG__MONGODB_HOST=mongodb
      - NODE_OPTIONS="--max-old-space-size=2048"
    depends_on:
      - mongodb
  nginx:
    image: "bitnami/nginx"
    ports:
      - "172.17.0.1:30247:8080"
    volumes:
      - "./nginx.server.conf:/opt/bitnami/nginx/conf/server_blocks/countly.conf:ro"
    depends_on:
      - countly-api
      - countly-frontend
